apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iuojvrju1-nodejs
  janus-idp.io/tekton: iuojvrju1-nodejs
  backstage.io/kubernetes-id: iuojvrju1-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iuojvrju1-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
